In [22]:
import pandas as pd, os, gc
import polars as pl
import mysql.connector
import numpy as np
from glob import glob
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

In [20]:
conn = mysql.connector.connect(
    host="118.179.149.162",
    user="gazu",
    password="X9!qR7@MZf#2A$wL8pE",
    database="padakhep",
    port=8837,
    buffered=True
)

### Demography Information

In [29]:
# member data
query = """
SELECT
z.name zone_name,
z.id zone_id,
z.pmuk_id zone_pmuk,
z.estd_date zone_estd_date,
z.is_active zone_status,



a.name area_name,
a.id area_id,
a.pmuk_id area_pmuk,
a.estd_date area_estd_date,
a.is_active area_status,


b.name as branch_name,
b.id branch_id,
b.pmuk_id branch_pmuk,
b.permanent_addr_thana,
b.estd_date branch_estd_date,
b.fundings,
b.is_active branch_status,

s.name shamity_name,
s.id shamity_id,
s.pmuk_id shamity_pmuk,
s.cm_employee_id,
s.member_cnt_initial,
s.member_cnt_min,
s.member_cnt_max,
s.shamity_type,
s.issue_date,
s.is_active shamity_ActiveStatus,
m.id  as mem_id,
m.pmuk_id member_pmuk,
m.gender,
m.phone,
m.religion,
m.nationality,
m.passport_expire_date,
m.smart_card_id,
m.nid,
m.marital_status,
m.dob,
m.occupation,
m.occupation_alt,
m.education,
m.permanent_addr_division,
m.shamity_block,
m.introducer_relation,
m.loan_component,
m.total_family_member,
m.total_earning_member,
m.total_monthly_income,
m.yearly_total_income,
m.yearly_total_expenses,
m.yearly_total_savings,
m.home_owner_type,
m.year_of_rent,
m.farm_land_amt,
m.loan_use_sources,
m.is_active member_status,
m.admission_date,
m.inactive_date
from members m
LEFT JOIN shamities s on s.id = m.shamity_id
LEFT JOIN branches b ON b.pmuk_id = LEFT(s.pmuk_id, 6)
LEFT JOIN areas a ON a.pmuk_id = LEFT(b.pmuk_id, 4)
LEFT JOIN zones z ON z.pmuk_id = LEFT(a.pmuk_id, 2)
where m.admission_date between '2026-02-01' and '2026-04-30'
    and z.name = 'Dhaka South Zone'
"""

In [30]:
member=pl.read_database(query, conn)

In [31]:
member.head()

shape: (5, 58)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ zone_name  ┆ zone_id ┆ zone_pmuk ┆ zone_estd ┆ … ┆ loan_use_ ┆ member_st ┆ admission ┆ inactive_ │
│ ---        ┆ ---     ┆ ---       ┆ _date     ┆   ┆ sources   ┆ atus      ┆ _date     ┆ date      │
│ str        ┆ i64     ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆ date      ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ <table    ┆ Yes       ┆ 2026-03-0 ┆           │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆ align="ce ┆           ┆ 2         ┆           │
│            ┆         ┆           ┆           ┆   ┆ nter"     ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ border="… ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ <table    ┆ Yes       ┆ 2026-03-0 ┆           │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆ align="ce ┆           ┆ 3         ┆           │
│            ┆         ┆           ┆           ┆   ┆ nter"     ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ border="… ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ <table    ┆ Yes       ┆ 2026-04-0 ┆           │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆ align="ce ┆           ┆ 5         ┆           │
│            ┆         ┆           ┆           ┆   ┆ nter"     ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ border="… ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ <table    ┆ Yes       ┆ 2026-04-2 ┆           │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆ align="ce ┆           ┆ 7         ┆           │
│            ┆         ┆           ┆           ┆   ┆ nter"     ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ border="… ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ <table    ┆ Yes       ┆ 2026-02-0 ┆           │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆ align="ce ┆           ┆ 3         ┆           │
│            ┆         ┆           ┆           ┆   ┆ nter"     ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ border="… ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [33]:
member['mem_id'].dtype

Int64

### Loan Informations

In [62]:
# loan information
query ="""
WITH filtered_members AS (
SELECT zones.name zonesName, zones.pmuk_id pmuk_ids, members.id as member_id, admission_date from members
LEFT JOIN shamities on shamities.id = members.shamity_id
JOIN zones
    ON zones.pmuk_id = LEFT(shamities.pmuk_id,2)
-- where shamities.pmuk_id like '01%' and admission_date BETWEEN '2026-02-01' AND '2026-04-30'
),

filtered_schedules AS (
    SELECT
    zonesName,
    pmuk_ids,
    filtered_members.member_id as mem_id,admission_date,
        ls.*
    FROM filtered_members
    LEFT JOIN loan_schedules ls on ls.member_id = filtered_members.member_id
    -- WHERE ls.due_date BETWEEN '2026-02-01' AND '2026-04-30'
)

SELECT
    zonesName,
    pmuk_ids,
    ls.mem_id,
    tl.shamity_id,

    lc.name AS loan_component,

    l.loan_product_id,
    l.id AS loan_id,
    l.disbursed_date,
    l.loan_amount,
    l.total_interest,
    l.balance,

    ls.id AS schedule_id,
    tl.id AS transaction_id,

    l.next_unpaid_schedule_id,
    l.is_active AS loan_activity,
    l.loan_condition,
    l.status AS loan_status,

    tl.transaction_type,
    l.overdue,

    -- schedule
    ls.kisti_no,
    ls.due_date,
    tl.date_of_action AS transaction_date,
    ls.kisti_amount,
    ls.principal_amount,
    ls.interest_amount,
    ls.paid_amount,
    tl.amount AS transaction_amount,
    ls.paid_principal,
    ls.paid_interest,
    ls.kisti_paid_date,
    ls.kisti_status,
    ls.is_holiday AS holiday,

    -- transaction loans
    tl.pre_sthiti,
    tl.pre_bokeya_sthiti,
    tl.post_sthiti,
    tl.post_bokeya_sthiti,
    tl.principal,
    tl.service_charge

FROM filtered_schedules ls

 INNER JOIN loans l
    ON l.id = ls.loan_id

LEFT JOIN transactions_loans tl
    ON tl.loan_id = l.id
    AND tl.loan_schedule_id = ls.id

LEFT JOIN loan_products lp
    ON lp.id = l.loan_product_id

LEFT JOIN loan_components lc
    ON lc.id = lp.component_id
where  l.id = 2123

"""

In [68]:
# loan_info=pl.read_database(query, conn)
loan_info=pd.read_sql(query, conn)
loan_info

,zonesName,pmuk_ids,mem_id,shamity_id,loan_component,loan_product_id,loan_id,disbursed_date,loan_amount,total_interest,...,paid_interest,kisti_paid_date,kisti_status,holiday,pre_sthiti,pre_bokeya_sthiti,post_sthiti,post_bokeya_sthiti,principal,service_charge
0,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
1,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
2,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
3,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
4,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
5,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
6,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
7,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
8,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
9,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
10,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
11,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
12,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
13,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
14,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
15,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
16,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
17,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
18,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
19,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
20,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
21,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-01,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
22,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-22,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
23,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-22,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
24,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-22,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
25,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,44450.0,12500.0,43200.0,11250.0,1106.0,144.0
26,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,43200.0,11250.0,40950.0,9000.0,1991.0,259.0
27,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,40950.0,9000.0,38700.0,6750.0,1991.0,259.0
28,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,38700.0,6750.0,36450.0,4500.0,1991.0,259.0
29,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,35450.0,14750.0,34200.0,13500.0,1106.0,144.0
30,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,36450.0,4500.0,35450.0,3500.0,885.0,115.0
31,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,34200.0,13500.0,31950.0,11250.0,1991.0,259.0
32,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,31950.0,11250.0,29700.0,9000.0,1991.0,259.0
33,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,29700.0,9000.0,27450.0,6750.0,1991.0,259.0
34,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,26450.0,14750.0,25200.0,13500.0,1106.0,144.0
35,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,27450.0,6750.0,26450.0,5750.0,885.0,115.0
36,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,25200.0,13500.0,22950.0,11250.0,1991.0,259.0
37,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,22950.0,11250.0,20700.0,9000.0,1991.0,259.0
38,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,20700.0,9000.0,18450.0,6750.0,1991.0,259.0
39,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,18450.0,6750.0,16200.0,4500.0,1991.0,259.0
40,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,16200.0,4500.0,13950.0,2250.0,1991.0,259.0
41,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,13950.0,2250.0,11700.0,0.0,1991.0,259.0
42,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,11700.0,0.0,9450.0,0.0,1991.0,259.0
43,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,9450.0,0.0,7200.0,0.0,1991.0,259.0
44,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,7200.0,0.0,4950.0,0.0,1991.0,259.0
45,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,4950.0,0.0,2700.0,0.0,1991.0,259.0
46,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,2700.0,0.0,450.0,0.0,1991.0,259.0
47,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,45,2021-11-17,paid,False,450.0,0.0,0.0,0.0,398.0,52.0
48,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,0,1990-09-09,unpaid,True,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
loan_info[loan_info['holiday']=='True']

,zonesName,pmuk_ids,mem_id,shamity_id,loan_component,loan_product_id,loan_id,disbursed_date,loan_amount,total_interest,...,paid_interest,kisti_paid_date,kisti_status,holiday,pre_sthiti,pre_bokeya_sthiti,post_sthiti,post_bokeya_sthiti,principal,service_charge
48,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,0,1990-09-09,unpaid,True,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
loan_info[loan_info["holiday"]== "False"].groupby('due_date')['transaction_date'].count().reset_index(name='transaction_count').sort_values(by='transaction_count', ascending=False)

      due_date  transaction_count
33  2021-10-03                  2
29  2021-09-05                  2
34  2021-10-10                  1
35  2021-10-17                  1
31  2021-09-19                  1
32  2021-09-26                  1
26  2021-08-08                  1
39  2021-11-14                  1
40  2021-11-21                  1
28  2021-08-29                  1
27  2021-08-22                  1
25  2021-08-01                  1
36  2021-10-24                  1
37  2021-10-31                  1
42  2021-12-05                  1
43  2021-12-12                  1
44  2021-12-19                  1
41  2021-11-28                  1
45  2021-12-26                  1
38  2021-11-07                  1
30  2021-09-12                  1
8   2021-04-04                  0
5   2021-03-14                  0
4   2021-03-07                  0
3   2021-02-28                  0
2   2021-02-21                  0
1   2021-02-14                  0
0   2021-02-07                  0
7   2021-03-28                  0
6   2021-03-21                  0
13  2021-05-09                  0
12  2021-05-02                  0
11  2021-04-25                  0
10  2021-04-18                  0
9   2021-04-11                  0
23  2021-07-18                  0
24  2021-07-25                  0
22  2021-07-11                  0
15  2021-05-23                  0
16  2021-05-30                  0
14  2021-05-16                  0
17  2021-06-06                  0
18  2021-06-13                  0
19  2021-06-20                  0
20  2021-06-27                  0
21  2021-07-04                  0

In [66]:
loan_info['transaction_count']=loan_info[loan_info["holiday"]== "False"].groupby('due_date')['transaction_date'].transform("count")

In [76]:
loan_info

,zonesName,pmuk_ids,mem_id,shamity_id,loan_component,loan_product_id,loan_id,disbursed_date,loan_amount,total_interest,...,paid_interest,kisti_paid_date,kisti_status,holiday,pre_sthiti,pre_bokeya_sthiti,post_sthiti,post_bokeya_sthiti,principal,service_charge
0,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
1,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
2,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
3,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
4,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
5,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
6,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
7,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
8,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
9,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
10,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
11,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
12,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
13,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
14,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
15,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
16,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
17,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
18,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
19,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
20,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,1990-09-09,past_paid,False,NaN,NaN,NaN,NaN,NaN,NaN
21,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-01,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
22,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-22,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
23,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-22,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
24,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-08-22,paid,False,NaN,NaN,NaN,NaN,NaN,NaN
25,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,44450.0,12500.0,43200.0,11250.0,1106.0,144.0
26,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,43200.0,11250.0,40950.0,9000.0,1991.0,259.0
27,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,40950.0,9000.0,38700.0,6750.0,1991.0,259.0
28,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-09-19,paid,False,38700.0,6750.0,36450.0,4500.0,1991.0,259.0
29,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,35450.0,14750.0,34200.0,13500.0,1106.0,144.0
30,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,36450.0,4500.0,35450.0,3500.0,885.0,115.0
31,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,34200.0,13500.0,31950.0,11250.0,1991.0,259.0
32,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,31950.0,11250.0,29700.0,9000.0,1991.0,259.0
33,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-10-18,paid,False,29700.0,9000.0,27450.0,6750.0,1991.0,259.0
34,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,26450.0,14750.0,25200.0,13500.0,1106.0,144.0
35,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,27450.0,6750.0,26450.0,5750.0,885.0,115.0
36,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,25200.0,13500.0,22950.0,11250.0,1991.0,259.0
37,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,22950.0,11250.0,20700.0,9000.0,1991.0,259.0
38,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,20700.0,9000.0,18450.0,6750.0,1991.0,259.0
39,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,18450.0,6750.0,16200.0,4500.0,1991.0,259.0
40,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,16200.0,4500.0,13950.0,2250.0,1991.0,259.0
41,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,13950.0,2250.0,11700.0,0.0,1991.0,259.0
42,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,11700.0,0.0,9450.0,0.0,1991.0,259.0
43,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,9450.0,0.0,7200.0,0.0,1991.0,259.0
44,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,7200.0,0.0,4950.0,0.0,1991.0,259.0
45,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,4950.0,0.0,2700.0,0.0,1991.0,259.0
46,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,259,2021-11-17,paid,False,2700.0,0.0,450.0,0.0,1991.0,259.0
47,Dhaka South Zone,01,3277,8383.0,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,45,2021-11-17,paid,False,450.0,0.0,0.0,0.0,398.0,52.0
48,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,0,1990-09-09,unpaid,True,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
loan_info[loan_info["holiday"]== "True"]

,zonesName,pmuk_ids,mem_id,shamity_id,loan_component,loan_product_id,loan_id,disbursed_date,loan_amount,total_interest,...,paid_interest,kisti_paid_date,kisti_status,holiday,pre_sthiti,pre_bokeya_sthiti,post_sthiti,post_bokeya_sthiti,principal,service_charge
48,Dhaka South Zone,01,3277,NaN,JAGORON,25,2123,2021-01-21,90000.0,11700.0,...,0,1990-09-09,unpaid,True,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
loan_info.groupby("due_date", as_index=False).agg(
        transaction_count=("transaction_date", "count"),
        holiday=("holiday", "first")
    )

      due_date  transaction_count holiday
0   2021-02-07                  0   False
1   2021-02-14                  0   False
2   2021-02-21                  0   False
3   2021-02-28                  0   False
4   2021-03-07                  0   False
5   2021-03-14                  0   False
6   2021-03-21                  0   False
7   2021-03-28                  0   False
8   2021-04-04                  0   False
9   2021-04-11                  0   False
10  2021-04-18                  0   False
11  2021-04-25                  0   False
12  2021-05-02                  0   False
13  2021-05-09                  0   False
14  2021-05-16                  0   False
15  2021-05-23                  0   False
16  2021-05-30                  0   False
17  2021-06-06                  0   False
18  2021-06-13                  0   False
19  2021-06-20                  0   False
20  2021-06-27                  0   False
21  2021-07-04                  0   False
22  2021-07-11                  0   False
23  2021-07-18                  0   False
24  2021-07-25                  0   False
25  2021-08-01                  1   False
26  2021-08-08                  1   False
27  2021-08-15                  0    True
28  2021-08-22                  1   False
29  2021-08-29                  1   False
30  2021-09-05                  2   False
31  2021-09-12                  1   False
32  2021-09-19                  1   False
33  2021-09-26                  1   False
34  2021-10-03                  2   False
35  2021-10-10                  1   False
36  2021-10-17                  1   False
37  2021-10-24                  1   False
38  2021-10-31                  1   False
39  2021-11-07                  1   False
40  2021-11-14                  1   False
41  2021-11-21                  1   False
42  2021-11-28                  1   False
43  2021-12-05                  1   False
44  2021-12-12                  1   False
45  2021-12-19                  1   False
46  2021-12-26                  1   False

In [36]:
demo_lone = member.join(
    loan_info,
    on='mem_id',
    how='right',
)

In [37]:
demo_lone

shape: (1_224, 94)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ zone_name  ┆ zone_id ┆ zone_pmuk ┆ zone_estd ┆ … ┆ post_sthi ┆ post_boke ┆ principal ┆ service_c │
│ ---        ┆ ---     ┆ ---       ┆ _date     ┆   ┆ ti        ┆ ya_sthiti ┆ ---       ┆ harge     │
│ str        ┆ i64     ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---       │
│            ┆         ┆           ┆ date      ┆   ┆ i64       ┆ i64       ┆           ┆ i64       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ 46368     ┆ 0         ┆ 3632      ┆ 1118      │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ 74188     ┆ 0         ┆ 5812      ┆ 1788      │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ 68832     ┆ 0         ┆ 5356      ┆ 2244      │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ 27564     ┆ 0         ┆ 2436      ┆ 414       │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ 25348     ┆ 0         ┆ 2216      ┆ 634       │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ 94950     ┆ 0         ┆ 1991      ┆ 259       │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ 92700     ┆ 0         ┆ 1991      ┆ 259       │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
│ Dhaka      ┆ 1       ┆ 01        ┆ 2004-01-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ South Zone ┆         ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Savings_Informations

In [41]:
# savings
savings ="""
WITH aggregated AS (
    SELECT
        t.member_id,
        SUM(CASE WHEN t.savings_type = 'rspw' AND t.transaction_type <> 'withdraw' THEN t.amount ELSE 0 END) AS rspw_deposit,
        SUM(CASE WHEN t.savings_type = 'rspw' AND t.transaction_type = 'withdraw' THEN t.amount ELSE 0 END) AS rspw_withdraw,
        SUM(CASE WHEN t.savings_type = 'rspm' AND t.transaction_type <> 'withdraw' THEN t.amount ELSE 0 END) AS rspm_deposit,
        SUM(CASE WHEN t.savings_type = 'rspm' AND t.transaction_type = 'withdraw' THEN t.amount ELSE 0 END) AS rspm_withdraw,
        SUM(CASE WHEN t.savings_type = 'vsp' AND t.transaction_type <> 'withdraw' THEN t.amount ELSE 0 END) AS vsps_deposit,
        SUM(CASE WHEN t.savings_type = 'vsp' AND t.transaction_type = 'withdraw' THEN t.amount ELSE 0 END) AS vsps_withdraw
    FROM transactions_savings t
    JOIN shamities s ON s.id = t.shamity_id
    WHERE s.pmuk_id LIKE '0102%'
      AND t.date_of_action BETWEEN '2026-02-01' AND '2026-04-30'
    GROUP BY t.member_id
),

latest_values AS (
    SELECT
        t.member_id,
        MAX(CASE WHEN t.savings_type = 'rspw' THEN t.post_sthiti ELSE 0 END) AS post_sthiti_rspw,
        MAX(CASE WHEN t.savings_type = 'rspm' THEN t.post_sthiti  ELSE 0 END) AS post_sthiti_rspm,
        MAX(CASE WHEN t.savings_type = 'vsp' THEN t.post_sthiti  ELSE 0 END) AS post_sthiti_vsp
    FROM (
        SELECT
            t.member_id,
            t.savings_type,
            t.post_sthiti,
            t.date_of_action,
            ROW_NUMBER() OVER (PARTITION BY t.member_id, t.savings_type ORDER BY t.date_of_action DESC) AS rn
        FROM transactions_savings t
        JOIN shamities s ON s.id = t.shamity_id
        WHERE s.pmuk_id LIKE '0102%'
    ) t
    WHERE rn = 1
    GROUP BY t.member_id
)

SELECT
    a.member_id,
    a.rspm_deposit,
    a.rspm_withdraw,
    l.post_sthiti_rspm,
    a.rspw_deposit,
    a.rspw_withdraw,
    l.post_sthiti_rspw,
    a.vsps_deposit,
    a.vsps_withdraw,
    l.post_sthiti_vsp
FROM aggregated a
LEFT JOIN latest_values l ON a.member_id = l.member_id
"""

In [42]:
savings_info=pl.read_database(savings, conn)
savings_info

shape: (2_841, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ member_id ┆ rspm_depo ┆ rspm_with ┆ post_sthi ┆ … ┆ post_sthi ┆ vsps_depo ┆ vsps_with ┆ post_sth │
│ ---       ┆ sit       ┆ draw      ┆ ti_rspm   ┆   ┆ ti_rspw   ┆ sit       ┆ draw      ┆ iti_vsp  │
│ i64       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ decimal[3 ┆ decimal[3 ┆ i64       ┆   ┆ i64       ┆ decimal[3 ┆ decimal[3 ┆ i64      │
│           ┆ 8,0]      ┆ 8,0]      ┆           ┆   ┆           ┆ 8,0]      ┆ 8,0]      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 995148    ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 17031     ┆ 2000      ┆ 0         ┆ 4000      ┆ … ┆ 29500     ┆ 1500      ┆ 0         ┆ 15142    │
│ 1195928   ┆ 0         ┆ 0         ┆ 500       ┆ … ┆ 8900      ┆ 0         ┆ 0         ┆ 260      │
│ 1218026   ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 8700      ┆ 0         ┆ 0         ┆ 60       │
│ 1204356   ┆ 500       ┆ 0         ┆ 1500      ┆ … ┆ 10050     ┆ 0         ┆ 0         ┆ 60       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 434933    ┆ 0         ┆ 42000     ┆ 0         ┆ … ┆ 138783    ┆ 0         ┆ 0         ┆ 3631     │
│ 953389    ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 1322077   ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 210       ┆ 0         ┆ 0         ┆ 0        │
│ 1313151   ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 360       ┆ 0         ┆ 0         ┆ 0        │
│ 21430     ┆ 2000      ┆ 0         ┆ 5000      ┆ … ┆ 41045     ┆ 0         ┆ 0         ┆ 5003     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
# area = """
# SELECT pmuk_id from areas where  pmuk_id like '01%' and is_active = 'yes'
# """
# areas=pl.read_database(area, conn)
# areas
# areas_list = areas['pmuk_id'].to_list()
# dfs = []
# for data in areas_list:
#     area_id = int(data)
#     print("Running for area_id:", area_id)
#
#     df = pl.read_database(
#         savings,
#         conn,
#         execute_options={"params": (area_id,area_id,)}
#     )
#     print("Rows:", df.shape[0])
#     dfs.append(df)
# final_df1 = pl.concat(dfs)
# final_df1.write_csv("savings_information.csv")